//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Linea = new HashSet<Linea>();
        }
    
        public int id { get; set; }
        public Nullable<double> descuento { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<int> efectivo { get; set; }
        public Nullable<double> monto_descuento { get; set; }
        public Nullable<double> monto_subtotal { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> iva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linea> Linea { get; set; }
    }
}
